### ISSUE TITLE
Header - Mobile 768 px

### ISSUE THREAD

**Issue by AmandaBalk** [maa-lin/my-first-git-project#1]
HTML och CSS

Ska innehålla (Se adlibris som exempel)
- företagsnamn 
- logga
- navbar 
      - sökruta  (ej funktion, endast synlig)
      - logga in-ikon 
      - varukorg-ikon

**Comment by feliziaboustedt** [comment]
Lägg till en stripe som går under nav-baren med info om att man kan köpa presentkort.
